auth = "devnet:devnet"

# The listening RPC address of bitcoind, port is usually 8332
daemon_rpc_addr = "bitcoin:18443"

# The listening P2P address of bitcoind, port is usually 8333
daemon_p2p_addr = "bitcoin:18444"

# Directory where the index should be stored. It should have at least 70GB of free space.
db_dir = "/opt"

# bitcoin means mainnet. Don't set to anything else unless you're a developer.
network = "regtest"

# The address on which electrs should listen. Warning: 0.0.0.0 is probably a bad idea!
# Tunneling is the recommended way to access electrs remotely.
electrum_rpc_addr = "0.0.0.0:60401"

# How much information about internal workings should electrs print. Increase before reporting a bug.
log_filters = "INFO"
